### ISSUE TITLE
Optimise the code

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/CricketScoreViewer#15]

**Comment by yashasvimatta** [comment]
Hi @swapnilsparsh could you please provide the description for the issue?

**Comment by swapnilsparsh** [comment]
@yashasvimatta You have to just optimise the code by keeping in mind the time complexity

**Comment by mangoomeh** [comment]
hi @swapnilsparsh can you assign me this? I think I can remove repeated code and fix the dark/light theme!

**Comment by swapnilsparsh** [comment]
ok @mangoomeh do the work

**Comment by swapnilsparsh** [comment]
Issue resolved by @mangoomeh
