### ISSUE TITLE
Possible Index Error

### ISSUE THREAD

**Issue by mangoomeh** [swapnilsparsh/CricketScoreViewer#17]
I apologize for my blunder, I found a possible chance that an IndexError might still be raised by python. During a live match, it might be possible that one team do not have any score yet and hence might raise an indexerror.

**Comment by swapnilsparsh** [comment]
@mangoomeh Solve it

**Comment by mangoomeh** [comment]
I got a pending pull request to solve the problem, please review

**Comment by swapnilsparsh** [comment]
@mangoomeh Great Work
