### ISSUE TITLE
Index Error

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/CricketScoreViewer#2]

**Comment by charchitmangal** [comment]
I would like to work this

**Comment by swapnilsparsh** [comment]
@charchithere OK, you can work on this issue

**Comment by charchitmangal** [comment]
@swapnilsparsh can you please elaborate more about Index Error

**Comment by swapnilsparsh** [comment]
![Error](https://user-images.githubusercontent.com/69387608/94785007-a0ceba80-03ec-11eb-89a9-a8c5be9f1731.png)

**Comment by IanFindlay** [comment]
I don't want to step on your toes @charchithere , but I was wanting a look at the gui for issue #1 and I've had to fix this issue in order to see it.

Are you still working on this? Is it alright with you, or @swapnilsparsh, if I PR my fix for this?

**Comment by swapnilsparsh** [comment]
@IanFindlay If you want to do you can also do the work.

**Comment by swapnilsparsh** [comment]
Ok Thank you for Solving this issue @IanFindlay
