### ISSUE TITLE
Score should be refreshed automatically (every 10-20 seconds)

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/CricketScoreViewer#5]

**Comment by sauravsolanki** [comment]
@swapnilsparsh Please assign me this.

**Comment by swapnilsparsh** [comment]
@sauravsolanki ok do the work

**Comment by sauravsolanki** [comment]
Why 10 sec? Should I keep 2 sec?

**Comment by sauravsolanki** [comment]
@swapnilsparsh Please checkout my PR.

**Comment by swapnilsparsh** [comment]
Resolve the conflict @sauravsolanki

**Comment by sauravsolanki** [comment]
@swapnilsparsh Resolved

**Comment by shrn2** [comment]
@swapnilsparsh  check my PR, i set refresh rate to 2seconds

**Comment by sauravsolanki** [comment]
@tre3x I already resolved the issue.

**Comment by swapnilsparsh** [comment]
@sauravsolanki Your PR is merged. Thank you for contributing in the project.
